People_MVC/Models/ViewModel/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace People_MVC.Models.ViewModel
{
    public class LoginViewModel
    {
        [Required]
        public string UserName { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

People_MVC/Controllers/AjaxController.cs
using Microsoft.AspNetCore.Mvc;
using People_MVC.Data;
using People_MVC.Models;
using People_MVC.Models.Repo;
using People_MVC.Models.Service;
using People_MVC.Models.ViewModel;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace People_MVC.Controllers
{
    [Authorize(Roles = "SuperAdmin,Admin,User")]
    public class AjaxController : Controller
    {
        private readonly IPeopleService _peopleService;
        private readonly IPeopleRepo _peopleRepo;
        readonly PeopleDbContext _context;
        PeopleService peopleService = new PeopleService();

        public static List<Person> _peopleList = new List<Person>();

        public AjaxController(IPeopleService peopleService, IPeopleRepo peopleRepo, PeopleDbContext context)
        {
            
            _peopleService = peopleService;
            _peopleRepo = peopleRepo;
            _context = context;
            
           
        }

       [HttpGet]
        public IActionResult ShowAll()
        {
            return PartialView("_ShowAll", _peopleService.All());
        }

        [HttpGet]
        public IActionResult Show(string searchId)
        {
            PeopleViewModel peopleSearch = new PeopleViewModel
            {
                Search = searchId
            };
            if (string.IsNullOrEmpty(peopleSearch.Search))
            {
                return PartialView("_Show", peopleService.All());
            }
            return PartialView(
                "_Show", peopleService.FindBy(peopleSearch));
        }

        //Get
        public IActionResult Management()
        {
            List<dynamic> oneList = new List<dynamic>();
            foreach (var item in _context.Persons)
            {
                dynamic dyObj = new ExpandoObject();
                dyObj.PId = item.PersonId;
                dyObj.CountryName = peopleService.GetCountryName(item.CityId);
                dyObj.PLanguage = peopleService.GetPersonLanguage(item.PersonId);

                oneList.Add(dyObj);
            }

            ViewBag.data = oneList;
            return View();
        }


        [HttpPost]
        public IActionResult PersonDetails(int ID)
        {      
            return PartialView("_PersonDetails",_peopleRepo.Read(ID));
        }

        [HttpPost]
        [Authorize(Roles = "Admin,SuperAdmin")]
        public IActionResult Delete(int ID)
        {            
            Person deletePerson = _peopleRepo.Read(ID);
            if (deletePerson!=null)
            {
                ViewBag.Message = $"Person with id {ID} has been deleted";
                return PartialView("_Delete", _peopleRepo.Delete(deletePerson));
            }
            else
            {
                ViewBag.Message = $"person with id {ID} is not exist.";
                return PartialView("_Delete", _peopleRepo.Delete(deletePerson));
            }
            //Person deletePerson = _peopleRepo.Read(ID);
            //return PartialView("_Delete", _peopleRepo.Delete(deletePerson));
        }
    }
}

People_MVC/Controllers/CitiesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using People_MVC.Models;
using People_MVC.Models.Service;
using People_MVC.Models.ViewModel;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PeopleMVC.Controllers
{
    [Authorize (Roles = "Admin,SuperAdmin")]
    public class CitiesController : Controller
    {
        
        private readonly ICityService _service;
        private readonly ICountryService _countryService;

        public CitiesController(ICityService service, ICountryService countryService)
        {
            this._service = service;
            this._countryService = countryService;
        }
        public IActionResult Index()
        {
            ViewBag.Countries = new SelectList(_countryService.All().Countries, "Id", "Name");

            return View(_service.All());
        }

        [HttpGet("cities/{id}")]
        public IActionResult GetCity(int id)
        {
            try
            {
                City city = _service.FindBy(id);
                return PartialView("City", city);
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult CreateCity(string cityName, string countryName)
        {
            if (ModelState.IsValid)
            {
                _service.Create(cityName,countryName);

            }

            return RedirectToAction("Index");
        }

        [HttpGet("cities/del/{id}")]
        public IActionResult DeleteCity(int id)
        {
            _service.Remove(id);
            return RedirectToAction("Index");
        }

  
    }
}

People_MVC/Controllers/CountriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using People_MVC.Models;
using People_MVC.Models.Service;
using People_MVC.Models.ViewModel;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PeopleMVC.Controllers
{
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class CountriesController : Controller
    {
        private readonly ICountryService _counrryService;
       
        public CountriesController(ICountryService service)
        {
            this._counrryService = service;
        }
        public IActionResult Index()
        {
            return View(_counrryService.All());
        }

        [HttpGet("/countries/{id}")]
        public IActionResult GetCountry(int id)
        {
            try
            {
                Country country = _counrryService.FindBy(id);
                return PartialView("Country", country);
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult CreateCountry(string countryName)
        {
            _counrryService.Add(countryName);
           
            return RedirectToAction("Index");
        }

        [HttpGet("/countries/del/{id}")]
        public IActionResult DeleteCountry(int id)
        {
            _counrryService.Remove(id);
            return RedirectToAction("Index");
        }



    }
}

People_MVC/Controllers/PeoplesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using People_MVC.Data;
using People_MVC.Models;
using People_MVC.Models.Repo;
using People_MVC.Models.Service;
using People_MVC.Models.ViewModel;
using System.Collections;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web.Mvc.Html;
using System.Web.WebPages.Html;
using SelectListItem = Microsoft.AspNetCore.Mvc.Rendering.SelectListItem;

namespace People_MVC.Controllers
{
    [AllowAnonymous]
    public class PeoplesController : Controller
    {
        private readonly IPeopleService _peopleService;
        readonly IPeopleRepo _peopleRepo;
        readonly PeopleDbContext _context;
        private readonly ICityService _cityService;
        private readonly ILanguageService _languageService;
        private readonly IPersonLanguageRepo _personLanguageRepo;


        public PeoplesController(IPeopleService peopleService, IPeopleRepo peopleRepo, PeopleDbContext context, ICityService cityService, ILanguageService languageService, IPersonLanguageRepo personLanguageRepo)
        {
            _peopleService = peopleService;
            _peopleRepo = peopleRepo;
            _context = context;
            _cityService = cityService;
            _languageService = languageService;
            _personLanguageRepo = personLanguageRepo;

        }

        [HttpGet]
        public IActionResult Index()
        {
            //PeopleViewModel vm = new PeopleViewModel();
            // vm.people = _context.Persons.ToList();
            //return View(vm);

            //if (InMemoryPeopleRepo.allPeopleList.Count == 0)
            //{
            //    InMemoryPeopleRepo.CreateDefaultPeoples();
            //}
            //return View(_peopleService.All());


            var query = from a in _context.Persons
                        join b in _context.Cities on a.CityId equals b.CityId
                        join c in _context.Countries on b.CountryId equals c.CountryId
                        join d in _context.PersonLanguages on a.PersonId equals d.PersonId
                        join e in _context.Languages on d.LanguageId equals e.LanguageId

                        select new { PId = a.PersonId, PName = a.Name, Phone = a.TeleNumber, CityName = b.Name, CountryName = c.Name, PLanguage = d.Language.Name};

            List < dynamic> oneList = new List<dynamic> ();


            foreach (var record in _context.Persons)
            {
              int tempId = record.PersonId;
              string tempLanguage = "";

              dynamic dyObj = new ExpandoObject();
                
              foreach (var item in query.ToList())
                {
                  if (item.PId == tempId)
                    {                    
                    dyObj.PId = item.PId;
                    dyObj.PName = item.PName;
                    dyObj.Phone = item.Phone;
                    dyObj.CityName = item.CityName;
                    dyObj.CountryName = item.CountryName;
                    tempLanguage = tempLanguage + " " + item.PLanguage;
                    }
                }
                  
                    dyObj.PLanguages = tempLanguage;
                    oneList.Add(dyObj);
               }   
                   
            ViewBag.data = oneList;

            //*System.NullReferenceException: 'Object reference not set to an instance of an object.'

            /*var cityList = _cityService.All().Cities.ToList();
            
            var selectItemList = new List<SelectListItem>() {
                new SelectListItem(){Value="1",Text="other",Selected=true}
            };
            var selectList = new SelectList(cityList, "CityListId","CityListName");
            selectItemList.AddRange(selectList);
            ViewBag.Cities = selectItemList; */

            ViewBag.Cities =  new SelectList(_cityService.All().Cities, "Id", "Name");
            ViewBag.Languages = new SelectList(_languageService.All().Languages, "LanguageId", "Name");

            return View();
        }

        public class CityList
        {
            public int CityListId { get; set; }
            public string CityListName { get; set; }
        }

        [HttpPost]
        public IActionResult Index(PeopleViewModel peopleViewModel)
        {
            //    peopleViewModel.PeopleList = _peopleService.FindBy(peopleViewModel.Search);
            //    return View(peopleViewModel);

            PeopleViewModel vm = new PeopleViewModel();
            vm.people = _context.Persons.ToList();

            if (!string.IsNullOrEmpty(peopleViewModel.Search))
            {
                var _peoples = from u in _context.Persons
                               where u.Name == peopleViewModel.Search
                               select u;

                _peoples = _context.Persons.Where(u => u.Name == peopleViewModel.Search);

                return View(_peoples);
            }
            else
            {
                return View(_context.Persons.ToList());
            }
        }

        [HttpPost]
        public IActionResult SearchSth(string search)
        {
            //var _peoples = from u in _context.Persons
            //               where u.Name.Contains(search)
            //               select u;

            //_peoples = _context.Persons.Where(u => u.Name == search);

            List<dynamic> resultList = new List<dynamic>();
            foreach (var item in ViewBag.data)
            {
                dynamic dySearchObj = new ExpandoObject();
                if (item.PName.Contains(search)
                    ||item.Phone.Contains(search) 
                    || item.CityName.Contains(search) 
                    || item.CountryName.Contains(search) 
                    || item.PLanguages.Contains(search))
                {
                    dySearchObj.PId = item.PId;
                    dySearchObj.PName = item.PName;
                    dySearchObj.Phone = item.Phone;
                    dySearchObj.CityName = item.CityName;
                    dySearchObj.CountryName = item.CountryName;
                    dySearchObj.PLanguages = item.PLanguage;
                    
                    resultList.Add(dySearchObj);
                }

                 ViewBag.SearchData = resultList;
            } 
        
            return PartialView("_SearchSth");       
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new CreatePersonViewModel());
        }

        [HttpPost]
        public IActionResult Create(Person person)
        {
            if (ModelState.IsValid)
             {
                _context.Persons.Add(person);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
             }
                return View(new CreatePersonViewModel());
        }
       
        [HttpGet]
        [Authorize(Roles = "Admin,SuperAdmin")]
        public IActionResult Delete(int id)
        {
            //_peopleService.Remove(id);
            Person deletePerson = _context.Persons.Find(id);
            _context.Persons.Remove(deletePerson);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Login()
        {
            ViewBag.LoginState = "Before login...";
            return View();
        }



        //[HttpPost]
        //public ActionResult Login(FormCollection fc)
        //{
        //    string email = fc["inputEmail3"];
        //    string password = fc["inputPassword3"];
        //    var user = _context.Persons.Where(b=>b.Email & base.Password == password);
        //    if (user.Count() > 0)
        //    {
        //        ViewBag.LoginState = email + "after login...";
        //    }
        //    else
        //    {
        //        ViewBag.LoginState = email + "don't exist.";

        //    }
        //    return View();
        //}
    }
}

People_MVC/Views/Shared/_Layout.cshtml
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - People_MVC</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">People_MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav ml-auto">
                        <partial name="_Login" />

                    </ul>
                </div>
            </div>


            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <form class="d-flex">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Ajax" asp-action="Management">Management</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Peoples" asp-action="Index">People</a>
                        </li>

                        @if (User.IsInRole("Admin,SuperAdmin"))
                        {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Languages" asp-action="Index">Languages</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Countries" asp-action="Index">Countries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Cities" asp-action="Index">Cities</a>
                        </li>
                       
                        }

                        @if (User.IsInRole("SuperAdmin"))
                        {
                       
                        <li class="nav-item active">
                            <a class="nav-link" asp-controller="Account"
                                asp-action="UserIndex">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                        </li>
                        }
                    </ul>
                </form>
            </div>

        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Wei Cao - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)

</body>

People_MVC/Views/Shared/_Login.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity.Name!</a>
        </li>
        <li class="nav-item">
            <form class="form-inline" asp-controller="User" asp-action="Logout">
                <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
            </form>
        </li>
 }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-white" asp-controller="Account" asp-action="Register">Register</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" asp-controller="Account" asp-action="Login">Login</a>
        </li>
}
</ul>